name: student_project

dependencies:

- numpy
- pandas
- jupyterlab
- statsmodels
- pip
- iPython
- scipy
- seaborn
- scikit-learn
- sympy
- ipywidgets
- future
- requests
- pyquery
- Pillow



- pip:
  


