name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
           activate-environment: testing
           environment-file: environment.yml
           python-version: 3.7
           auto-activate-base: false
    - name: execute notebooks
      shell: bash -l {0}
      run: |
        . scl_source enable devtoolset-7 || true
        . scl_source enable llvm-toolset-6.0 || true
        . /etc/profile.d/modules.sh || true
        module load mpi
        . $INSTALL_DIR/bin/thisbdm.sh
        xvfb-run -d -s "-screen 0 2560x1440x24" make run-demos
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        jupyter nbconvert --execute --ExecutePreprocessor.timeout=-1 *.ipynb